name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 evita el problema del shallow clone

      - name: Configurar Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git remote remove heroku || true
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Push a Heroku
        run: git push heroku HEAD:main --force
